Show page chart
ololyay/observer pull request #10
Opened 2016-10-04 15:42 UTC by nbondarenko

2016-10-04 16:07 UTC, tilast requested changes

2016-10-04 16:07 UTC, tilast commented on et
> +=> {[31m[1;31m"[0m[31m2016-10-03 11:50:12[1;31m"[0m[31m[0m=>[1;34m0[0m,
do we need this file at all?

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
> +    var max = Math.max.apply(Math, log);
```js
  var max = _.max(log) || _.max(logOfFails);
```

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
>        }
plz omit any constructions without the `{}`, like for `if` or `else`

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
> +        $("div[data-id="+ i +"]").width(100/amount+"%").height(299/max*log[i]).addClass("hint--bottom hint--small").attr("aria-label", logOfTimes[i]);
`100`, `299` - magic numbers?

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
> +        $("div[data-id="+ i +"]").width(100/amount+"%").height(299/max*log[i]).addClass("hint--bottom hint--small").attr("aria-label", logOfTimes[i]);
plz prefer using `'` over the `"`

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
> +        $("div[data-id="+ i +"]").append("<span>" + logOfTimes[i].slice(11) + "</span>");
`11` - magic number?

2016-10-04 16:07 UTC, tilast commented on frontend/js/response_chart.js
> +      if(i%20 == 0){
`20` - magic number?

2016-10-04 16:07 UTC, tilast commented on gulpfile.js
> +    // 'bower_components/tooltipster/dist/css/tooltipster.bundle.min.css',
plz remove or uncomment commented code

2016-10-05 09:34 UTC, denysxftr requested changes
plz rework a bit data structure which you pass from controller and make related changes in js

2016-10-05 09:34 UTC, ololyay commented on app/controllers/checks_controller.rb
> +  json({ log: log, fails_log: fails_log, issues_log: issues_log })
you can remove useless code here
plz use only `log` var which has structure like 
```ruby
[
  { time: '12:30:21', issues: 'joined issues here', response_time: 456 },
  { time: '12:35:15', issues: 'joined issues here', response_time: 317 }
]
```
and make appropriate changes in js file

2016-10-05 11:59 UTC, tilast commented on frontend/js/response_chart.js
> +      if(log[i]){
plz read https://github.com/airbnb/javascript

2016-10-05 12:22 UTC, denysxftr requested changes

2016-10-05 12:22 UTC, ololyay commented on frontend/js/response_chart.js
> +      parentContainer.append('<div class= "chart-bar" data-id='+ index +'></div>');
```js
var bar = $('<div class="chart-bar" data-id=' + index + '></div>');
```

2016-10-05 14:48 UTC, tilast approved these changes
ok for me, but let's wait for @ololyay

2016-10-05 15:29 UTC, dvoitekh commented on app/controllers/checks_controller.rb
> +  json({ log: prepare_logs(results)})
add space before `}` please

2016-10-05 15:30 UTC, dvoitekh approved these changes

2016-10-05 15:35 UTC, dvoitekh commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
too many spaces here (remove one after `=>` and one after `}`)

2016-10-05 16:58 UTC, denysxftr approved these changes
nice
plz fix @dvoitekh comments

2016-10-05 18:13 UTC, dvoitekh commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
please try using 
```es6
var maxOfTimeouts = _.maxBy(log, item => item.timeout ).timeout;
```

2016-10-05 18:53 UTC, tilast commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
do we have a es6 here? @ololyay

2016-10-05 18:54 UTC, ololyay commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
nope

2016-10-05 19:08 UTC, tilast commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
well then it will not work at all, should be a syntax error

2016-10-05 19:18 UTC, dvoitekh commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
¯\_(ツ)_/¯

2016-10-05 19:31 UTC, nbondarenko commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
there are no errors, but I'll check

2016-10-05 19:32 UTC, tilast commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
well there is no error in chrome because it supports es6 natively
but I'd not rely on that

2016-10-05 19:45 UTC, nbondarenko commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
works in firefox too

2016-10-05 19:53 UTC, tilast commented on frontend/js/response_chart.js
> +    var maxOfTimeouts = _.maxBy(log, item =>  { return item.timeout; } ).timeout;
I know, one of the _latest_ firefoxes
but the browsers support is still poor
https://kangax.github.io/compat-table/es6/

2016-10-05 21:43 UTC, tilast approved these changes

2016-10-06 05:23 UTC, merged