Code climate
ololyay/observer pull request #13
Opened 2016-10-10 12:48 UTC by nbondarenko

2016-10-10 13:22 UTC, dvoitekh commented on app/controllers/checks_controller.rb
> +  @check = Check.new( check_params )
please remove spaces around braces

2016-10-10 13:22 UTC, dvoitekh commented on app/controllers/checks_controller.rb
> +  @check.update( check_params )
and here too

2016-10-10 13:22 UTC, dvoitekh commented on app/controllers/servers_controller.rb
> +  @server = Server.new( server_params )
and here

2016-10-10 13:22 UTC, dvoitekh commented on app/controllers/servers_controller.rb
> +  @server.update( server_params )
and here

2016-10-10 13:23 UTC, dvoitekh commented
looks good

2016-10-10 15:32 UTC, dvoitekh commented on app/helpers/application_helper.rb
> +    name: params[name]
`params[:name]`

2016-10-11 12:53 UTC, denysxftr requested changes
awesome but see some comments

2016-10-11 12:53 UTC, ololyay commented on app/controllers/checks_controller.rb
> +  validate_instance @check
lets rename it to `finish_action` because method doesn't do any validations

2016-10-11 12:53 UTC, ololyay commented on app/helpers/application_helper.rb
> +  params.select { |k, v| accepted_params.include?(k) }
make `_` instead of `v`

2016-10-11 15:35 UTC, denysxftr requested changes
one more comment

2016-10-11 15:35 UTC, ololyay commented on app/controllers/checks_controller.rb
> +  update_finish_action @check
`finish_update_action`

2016-10-13 13:09 UTC, denysxftr approved these changes
well done

2016-10-13 15:57 UTC, merged